# pack_repo.py — flatten the lab into ONE markdown file for external LLM review
# (a local code2prompt: no install, no repo access needed by the reviewer).
#
#   .venv/bin/python pack_repo.py          -> writes repo_pack.md (gitignored)
#
# Ordered for a cold reader: CURRENT_STATE.md first (the status map — prevents the
# review-the-retired-screener-as-the-product misread), then code in dependency order,
# tests last. Data/caches/artifacts excluded. Regenerate fresh before each share.
#
# PRIVACY NOTE (shown at run time too): the pack contains portfolio.py (real holdings)
# and the SEC contact email in edgar.py. Fine to share with an LLM chat you trust;
# strip those files below if not.

from pathlib import Path

ROOT = Path(__file__).resolve().parent
OUT = ROOT / "repo_pack.md"

# Explicit front matter + core order; everything else picked up alphabetically after.
FIRST = [
    "CURRENT_STATE.md",
    "requirements.txt",
    "config.py",
    "fundamentals.py",
    "edgar.py",
    "factors.py",
    "score.py",
    "screen.py",
    "export.py",
    "portfolio.py",
    "backtest/constants.py",
    "backtest/costs.py",
    "backtest/metrics.py",
    "backtest/engine.py",
    "backtest/engine_xs.py",
    "backtest/trend_sleeve.py",
    "backtest/timing_luck.py",
    "backtest/significance.py",
    "backtest/leverage_study.py",
    "backtest/synthetic.py",
    "backtest/volatility.py",
    "backtest/tracker.py",
    "backtest/dashboard.py",
    "backtest/preflight.py",
]
SKIP_DIRS = {".git", ".venv", "__pycache__", "output", "cache", "data"}
SKIP_FILES = {OUT.name, "desk_data.json", "desk_history.json", "desk_daily.csv"}
KEEP_EXT = {".py", ".md", ".txt"}


def wanted(p: Path) -> bool:
    rel = p.relative_to(ROOT)
    if any(part in SKIP_DIRS for part in rel.parts) or p.name in SKIP_FILES:
        return False
    if rel.parts[0] == "backtest" and rel.parts[1:2] == ("picks",):
        return False                       # lock JSONs are data, not code
    return p.suffix in KEEP_EXT


def main():
    files = [ROOT / f for f in FIRST if (ROOT / f).exists()]
    rest = sorted(p for p in ROOT.rglob("*") if p.is_file() and wanted(p)
                  and str(p.relative_to(ROOT)) not in FIRST)
    # experiments + tests after core, tests very last
    rest.sort(key=lambda p: (p.parts.__contains__("tests"), str(p)))
    files += rest

    parts = ["# SystematicEquityFactorScreener — full repo pack\n",
             "*Generated by pack_repo.py. Read CURRENT_STATE.md (first file) before "
             "judging anything: this repo contains LIVE strategies, RETIRED negative "
             "results kept on purpose, and BANKED options — it is not one product.*\n"]
    total_lines = 0
    for p in files:
        rel = p.relative_to(ROOT)
        text = p.read_text(errors="replace").rstrip("\n")
        total_lines += text.count("\n") + 1
        fence = "```" if p.suffix != ".md" else "````"
        lang = {".py": "python", ".txt": "text", ".md": "markdown"}[p.suffix]
        parts.append(f"\n---\n## FILE: {rel}\n{fence}{lang}\n{text}\n{fence}\n")
    out = "\n".join(parts)
    OUT.write_text(out)
    print(f"wrote {OUT.name}: {len(files)} files, {total_lines:,} lines, "
          f"{len(out):,} chars (~{len(out) // 4:,} tokens)")
    print("PRIVACY: includes portfolio.py (real holdings) + contact email in edgar.py.")


if __name__ == "__main__":
    main()
